apiVersion: v1
kind: Service
metadata:
  name: clembot-api
  namespace: clembot
  labels:
    app: clembot-api
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: clembot-api
